included:
  - Spaceman
  - SpacemanTests

excluded:
  - Spaceman.xcodeproj
  - Images
  - .build
  - DerivedData

disabled_rules:
  - todo

analyzer_rules:
  - unused_import
  - capture_variable

opt_in_rules:
  - array_init
  - closure_end_indentation
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_cast
  - force_try
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - return_value_from_void_function
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - yoda_condition

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

identifier_name:
  excluded:
    - id
    - to
    - in
    - on

reporter: xcode
